#!/bin/bash

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_2d_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/2d.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_assets_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/assets.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_audio_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/audio.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_cocos_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/cocos.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_dragonbones_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/dragonbones.i


swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_editor_support_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/editor_support.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_extension_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/extension.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_geometry_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/geometry.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_gfx_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/gfx.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_network_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/network.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_physics_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/physics.i


swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_pipeline_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/pipeline.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_scene_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/scene.i



swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_spine_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/spine.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_webview_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/webview.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_video_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/video.i

swig -c++ -cocos -fvirtual -noexcept -cpperraswarn -Dfinal= -DCC_PLATFORM=3 -Dconstexpr=const -DCC_PLATFORM_ANDROID=3 -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native -I/Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos -o /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/cocos/bindings/auto/jsb_render_auto.cpp /Users/james/Project/cocos/cocos-creator/cocos-editor/resources/3d/engine/native/tools/swig-config/renderer.i